package com.pulsedeck.app.settings.model

data class ThirdPartyLicenseNotice(
    val name: String,
    val artifacts: List<String>,
    val version: String,
    val license: String,
    val copyright: String,
    val url: String,
    val note: String = "",
)

data class ThirdPartyNotice(
    val name: String,
    val artifacts: List<String>,
    val version: String,
    val license: String,
    val copyright: String,
    val homepage: String,
    val usage: String,
    val attributionRequired: Boolean,
    val copyleftOrUnknownFlag: Boolean,
    val allowedForRelease: Boolean,
    val note: String = "",
)

private fun ThirdPartyLicenseNotice.toReleaseAuditNotice(): ThirdPartyNotice {
    val normalizedLicense = license.lowercase()
    val flagged = normalizedLicense.contains("gpl") ||
        normalizedLicense.contains("unknown") ||
        normalizedLicense.contains("pending") ||
        normalizedLicense.contains("terms")
    return ThirdPartyNotice(
        name = name,
        artifacts = artifacts,
        version = version,
        license = license,
        copyright = copyright,
        homepage = url,
        usage = note.ifBlank { "Runtime dependency or platform service used by PulseDeck." },
        attributionRequired = true,
        copyleftOrUnknownFlag = flagged,
        allowedForRelease = !flagged,
        note = note,
    )
}

object PulseDeckThirdPartyLicenses {
    val runtimeInventory: List<ThirdPartyLicenseNotice> = listOf(
        ThirdPartyLicenseNotice(
            name = "Kotlin",
            artifacts = listOf("org.jetbrains.kotlin:kotlin-stdlib"),
            version = "2.1.0",
            license = "Apache License 2.0",
            copyright = "JetBrains and Kotlin contributors",
            url = "https://kotlinlang.org/",
        ),
        ThirdPartyLicenseNotice(
            name = "AndroidX Core KTX",
            artifacts = listOf("androidx.core:core-ktx"),
            version = "1.15.0",
            license = "Apache License 2.0",
            copyright = "The Android Open Source Project",
            url = "https://developer.android.com/jetpack/androidx",
        ),
        ThirdPartyLicenseNotice(
            name = "AndroidX Activity Compose",
            artifacts = listOf("androidx.activity:activity-compose"),
            version = "1.10.0",
            license = "Apache License 2.0",
            copyright = "The Android Open Source Project",
            url = "https://developer.android.com/jetpack/androidx",
        ),
        ThirdPartyLicenseNotice(
            name = "Jetpack Compose",
            artifacts = listOf(
                "androidx.compose.ui:ui",
                "androidx.compose.ui:ui-tooling-preview",
                "androidx.compose.ui:ui-tooling",
                "androidx.compose.material3:material3",
            ),
            version = "2025.01.01 BOM",
            license = "Apache License 2.0",
            copyright = "The Android Open Source Project",
            url = "https://developer.android.com/jetpack/compose",
            note = "UI tooling is packaged only for debug builds.",
        ),
        ThirdPartyLicenseNotice(
            name = "AndroidX DataStore",
            artifacts = listOf("androidx.datastore:datastore-preferences"),
            version = "1.1.1",
            license = "Apache License 2.0",
            copyright = "The Android Open Source Project",
            url = "https://developer.android.com/topic/libraries/architecture/datastore",
        ),
        ThirdPartyLicenseNotice(
            name = "AndroidX Media3",
            artifacts = listOf(
                "androidx.media3:media3-common",
                "androidx.media3:media3-database",
                "androidx.media3:media3-datasource",
                "androidx.media3:media3-exoplayer",
                "androidx.media3:media3-session",
            ),
            version = "1.10.1",
            license = "Apache License 2.0",
            copyright = "The Android Open Source Project",
            url = "https://developer.android.com/media/media3",
        ),
        ThirdPartyLicenseNotice(
            name = "AndroidX Room",
            artifacts = listOf("androidx.room:room-runtime", "androidx.room:room-ktx"),
            version = "2.6.1",
            license = "Apache License 2.0",
            copyright = "The Android Open Source Project",
            url = "https://developer.android.com/training/data-storage/room",
        ),
        ThirdPartyLicenseNotice(
            name = "AndroidX WorkManager",
            artifacts = listOf("androidx.work:work-runtime-ktx"),
            version = "2.10.0",
            license = "Apache License 2.0",
            copyright = "The Android Open Source Project",
            url = "https://developer.android.com/topic/libraries/architecture/workmanager",
        ),
        ThirdPartyLicenseNotice(
            name = "NewPipe Extractor",
            artifacts = listOf("com.github.teamnewpipe:newpipeextractor"),
            version = "0.26.2",
            license = "GPL-3.0-or-later",
            copyright = "Team NewPipe contributors",
            url = "https://github.com/TeamNewPipe/NewPipeExtractor",
            note = "Used for supported online media metadata and stream extraction paths.",
        ),
        ThirdPartyLicenseNotice(
            name = "Oboe",
            artifacts = listOf("com.google.oboe:oboe"),
            version = "1.10.0",
            license = "Apache License 2.0",
            copyright = "Google LLC and contributors",
            url = "https://github.com/google/oboe",
        ),
        ThirdPartyLicenseNotice(
            name = "Google Play services TensorFlow Lite",
            artifacts = listOf(
                "com.google.android.gms:play-services-tflite-java",
                "com.google.android.gms:play-services-tflite-gpu",
            ),
            version = "16.5.0",
            license = "Google Play services terms",
            copyright = "Google LLC",
            url = "https://developers.google.com/terms",
            note = "Used for optional on-device recommendation model runtime support.",
        ),
        ThirdPartyLicenseNotice(
            name = "Android desugar JDK libraries",
            artifacts = listOf("com.android.tools:desugar_jdk_libs_nio"),
            version = "2.1.5",
            license = "Apache License 2.0",
            copyright = "The Android Open Source Project",
            url = "https://github.com/google/desugar_jdk_libs",
        ),
    )

    val releaseAuditInventory: List<ThirdPartyNotice> =
        runtimeInventory.map { it.toReleaseAuditNotice() } + listOf(
            ThirdPartyNotice(
                name = "KoreanThinker Billboard JSON",
                artifacts = listOf("github.com/KoreanThinker/billboard-json JSON chart snapshots"),
                version = "main branch hosted JSON",
                license = "GPL-3.0",
                copyright = "KoreanThinker/billboard-json contributors",
                homepage = "https://github.com/KoreanThinker/billboard-json",
                usage = "Optional hosted Billboard chart source consumed as JSON data.",
                attributionRequired = true,
                copyleftOrUnknownFlag = true,
                allowedForRelease = false,
                note = "GitHub repository metadata lists GPL-3.0. Confirm distribution implications before release.",
            ),
            ThirdPartyNotice(
                name = "mhollingshead Billboard Hot 100",
                artifacts = listOf("github.com/mhollingshead/billboard-hot-100 recent.json"),
                version = "main branch hosted JSON",
                license = "No license detected in visible repository metadata",
                copyright = "mhollingshead/billboard-hot-100 contributors",
                homepage = "https://github.com/mhollingshead/billboard-hot-100",
                usage = "Optional hosted Hot 100 chart source consumed as JSON data.",
                attributionRequired = true,
                copyleftOrUnknownFlag = true,
                allowedForRelease = false,
                note = "Treat as all-rights-reserved/pending legal review until a license is confirmed.",
            ),
            ThirdPartyNotice(
                name = "Radio Browser API",
                artifacts = listOf("api.radio-browser.info public station directory"),
                version = "hosted public API",
                license = "Free/open API terms",
                copyright = "Radio Browser contributors",
                homepage = "https://api.radio-browser.info/",
                usage = "PulseRadio station directory metadata.",
                attributionRequired = true,
                copyleftOrUnknownFlag = false,
                allowedForRelease = true,
                note = "API docs ask clients to use a speaking HTTP user-agent and avoid pinning one server.",
            ),
            ThirdPartyNotice(
                name = "LRCLIB",
                artifacts = listOf("lrclib.net lyrics API"),
                version = "hosted public API",
                license = "Service terms pending audit",
                copyright = "LRCLIB contributors and lyric rightsholders",
                homepage = "https://lrclib.net/docs",
                usage = "Optional plain/synced lyrics lookup when network policy allows.",
                attributionRequired = true,
                copyleftOrUnknownFlag = true,
                allowedForRelease = false,
                note = "Lyrics text must not be logged or bundled; release needs terms/rightsholder review.",
            ),
            ThirdPartyNotice(
                name = "lyrics.ovh",
                artifacts = listOf("lyrics.ovh plain lyrics API"),
                version = "hosted public API",
                license = "Service terms pending audit",
                copyright = "lyrics.ovh and lyric rightsholders",
                homepage = "https://lyrics.ovh/",
                usage = "Plain lyrics fallback when network policy allows.",
                attributionRequired = true,
                copyleftOrUnknownFlag = true,
                allowedForRelease = false,
                note = "Lyrics text must not be logged or bundled; release needs terms/rightsholder review.",
            ),
            ThirdPartyNotice(
                name = "MusicBrainz + Cover Art Archive",
                artifacts = listOf("musicbrainz.org metadata", "coverartarchive.org artwork references"),
                version = "hosted public APIs",
                license = "Open data/service terms",
                copyright = "MetaBrainz Foundation and Internet Archive contributors",
                homepage = "https://musicbrainz.org/",
                usage = "Album metadata and artwork discovery.",
                attributionRequired = true,
                copyleftOrUnknownFlag = false,
                allowedForRelease = true,
                note = "Credit MusicBrainz, Cover Art Archive, MetaBrainz Foundation, and Internet Archive in notices.",
            ),
        )
}
